"""fix_enum_casing_to_lowercase

Revision ID: 34b68ed65ece
Revises: 9ec8250584c4
Create Date: 2025-07-19 20:51:05.223475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b68ed65ece'
down_revision: Union[str, Sequence[str], None] = '9ec8250584c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
