"""Add Skycaster pricing and weather request models

Revision ID: 92504e1229b5
Revises: 792079e929c2
Create Date: 2025-07-17 16:14:21.691771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92504e1229b5'
down_revision: Union[str, Sequence[str], None] = '792079e929c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('currency_code', sa.String(length=5), nullable=False),
    sa.Column('currency_symbol', sa.String(length=10), nullable=False),
    sa.Column('currency_name', sa.String(length=50), nullable=False),
    sa.Column('country_codes', sa.Text(), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_code')
    )
    op.create_table('variable_mapping',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('variable_name', sa.String(length=100), nullable=False),
    sa.Column('endpoint_type', sa.String(length=20), nullable=False),
    sa.Column('endpoint_url', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variable_name')
    )
    op.create_table('pricing_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('variable_name', sa.String(length=100), nullable=False),
    sa.Column('endpoint_type', sa.String(length=20), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('tax_enabled', sa.Boolean(), nullable=False),
    sa.Column('hsn_sac_code', sa.String(length=20), nullable=True),
    sa.Column('free_plan_price', sa.Float(), nullable=True),
    sa.Column('developer_plan_price', sa.Float(), nullable=True),
    sa.Column('business_plan_price', sa.Float(), nullable=True),
    sa.Column('enterprise_plan_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variable_name')
    )
    op.create_table('weather_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('api_key_id', sa.String(), nullable=False),
    sa.Column('locations', sa.Text(), nullable=False),
    sa.Column('variables', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('endpoints_called', sa.Text(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_time', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('tax_applied', sa.Float(), nullable=False),
    sa.Column('final_amount', sa.Float(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_requests')
    op.drop_table('pricing_config')
    op.drop_table('variable_mapping')
    op.drop_table('currency_config')
    # ### end Alembic commands ###
